version: '2.0'
volumes:
  database:
    external: true
services:
    db:
      image: "mysql:5.7"
      container_name: "app_database"
      restart: always
      networks:
        - app
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
      volumes:
        - database:/var/lib/mysql

    php:
        build:
          dockerfile: Dockerfile
          context: "./app"
        container_name: "app_php"
        networks:
          - app
#        volumes:
#          - ./app:/var/www/html
        links:
            - db
        depends_on:
            - db

    nginx:
        image: nginx:latest
        container_name: "app_nginx"
        depends_on:
          - php
        links:
          - php
        networks:
          - app
        ports:
            - ${NGINX_PORT}
        volumes:
            - ./app:/var/www/html
            - ./config/nginx:/etc/nginx/conf.d

    phpmyadmin:
      image: "phpmyadmin/phpmyadmin"
      restart: always
      container_name: "app_pma"
      networks:
        - app
      links:
        - db
      environment:
        PMA_HOST: db
        PMA_PORT: 3306
        PMA_ARBITRARY: 1
      ports:
        - ${PMA_PORT}
networks:
  app:
    driver: bridge
