
version: '3.2'
volumes:
  data:
    external:
      name: test
  database:
    external: true
  nginx:
    external: true
services:
    php:
        image: 'ivanhunt/phpserv:latest'
        container_name: app-php
        networks:
          - app
        volumes:
          - ./app:/var/www/html
        depends_on:
            - db
        deploy:
          replicas: 2
          restart_policy:
            condition: on-failure
          placement:
            constraints:
              - node.role == worker
    nginx:
        image: nginx:latest
        container_name: app-nginx
        depends_on:
          - php
        links:
          - php
        networks:
          - app
        ports:
            - '8083:80'
        volumes:
            - ./app:/var/www/html
            - ./config/nginx:/etc/nginx/conf.d
        deploy:
          replicas: 1
          restart_policy:
            condition: on-failure
          placement:
            constraints:
              - node.role == manager


    db:
      image: "mysql:5.7"
      restart: always
      container_name: "database"
      networks:
        - app
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: test
        MYSQL_USER: test
        MYSQL_PASSWORD: 123
      ports:
        - "3306:3306"
      volumes:
        - database:/var/lib/mysql
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure
        placement:
          constraints:
            - node.labels.db == true

    phpmyadmin:
      image: "phpmyadmin/phpmyadmin"
      restart: always
      container_name: "pma"
      networks:
        - app
      links:
        - db
      environment:
        PMA_HOST: db
        PMA_PORT: 3306
        PMA_ARBITRARY: 1
      ports:
        - 8085:80
      env_file: .env
      deploy:
        replicas: 1
        placement:
          constraints:
            - node.labels.db == true
networks:
  app:
    driver: overlay
