
version: '3.2'
volumes:
  database:
    external: true
services:
    php:
        build:
          dockerfile: Dockerfile
          context: "./app"
        container_name: app-php
        networks:
          - app
        volumes:
          - ./app:/var/www/html
        links:
            - db
        depends_on:
            - db
    nginx:
        image: nginx:latest
        container_name: app-nginx
        depends_on:
          - php
        links:
          - php
        networks:
          - app
        ports:
            - '7070:80'
        volumes:
            - ./app:/var/www/html
            - ./config/nginx:/etc/nginx/conf.d

    db:
      image: "mysql:5.7"
      restart: always
      container_name: "database"
      networks:
        - app
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: test
        MYSQL_USER: test
        MYSQL_PASSWORD: 123
      volumes:
        - database:/var/lib/mysql

    phpmyadmin:
      image: "phpmyadmin/phpmyadmin"
      restart: always
      container_name: "pma"
      networks:
        - app
      links:
        - db
      environment:
        PMA_HOST: db
        PMA_PORT: 3306
        PMA_ARBITRARY: 1
      ports:
        - 8085:80
networks:
  app:
    driver: bridge
